
    TERRAIN_2A = $2A ; blue lord?

    TERRAIN_VILLAGE_OPENED = $A5
    TERRAIN_VILLAGE_DESTROYED = $A9
    TERRAIN_CHEST_CLOSED = $AB
    TERRAIN_CHEST_OPENED = $AC
    TERRAIN_HOUSE_DESTROYED = $AD
